//! # from-hana-to-kafka
//!
//! Консольное приложение на **Rust**: подключается к **SAP HANA** по **ODBC**, обеспечивает наличие
//! таблицы `USERS`, читает строки в `Vec<UserRow>` и отправляет их в **Apache Kafka** одним
//! JSON-сообщением.
//!
//! Конфигурация берётся из `.env` (см. [`env_work`]): `HANA_ODBC_CONNECTION`, `KAFKA_BROKERS`,
//! `KAFKA_TOPIC`, `KAFKA_TIMEOUT`, `KAFKA_CONNECT_TIMEOUT`.
//!
//! Логи пишутся через `tracing` в каталог `hana_logs/` (см. [`my_log`]).
//!
//! ## Документация API (rustdoc)
//!
//! ```text
//! cargo doc --no-deps --open
//! ```
//!
mod env_work;
mod kafka;
mod my_log;

use serde::{Deserialize, Serialize};

/// Точка входа: подключение к SAP HANA (ODBC), обеспечение таблицы `USERS`, чтение пользователей и отправка в Kafka.
#[tokio::main]
async fn main() {
    env_work::ensure_dotenv_loaded();
    let _log_guard = my_log::init();

    // Пробуем установить ODBC-соединение с SAP HANA и логируем результат.
    let conn_str = env_work::HANA_ODBC_CONNECTION.as_str();
    let env = match odbc_api::Environment::new() {
        Ok(env) => env,
        Err(e) => {
            tracing::error!(error = %e, "не удалось создать ODBC Environment");
            return;
        }
    };

    let mut conn = match env.connect_with_connection_string(conn_str, odbc_api::ConnectionOptions::default()) {
        Ok(conn) => {
            tracing::info!("ODBC соединение с SAP HANA установлено успешно");
            conn
        }
        Err(e) => {
            tracing::error!(error = %e, "ошибка ODBC соединения с SAP HANA");
            return;
        }
    };

    // Создать таблицу USERS при отсутствии.
    match ensure_users_table(&mut conn) {
        Ok(UsersTableAction::AlreadyExists) => {
            tracing::info!("таблица USERS уже существует");
        }
        Ok(UsersTableAction::Created) => {
            tracing::info!("таблица USERS создана");
        }
        Err(e) => {
            tracing::error!(error = %e, "ошибка при создании таблицы USERS");
            return;
        }
    }

    // Добавить тестовых пользователей.
    match insert_sample_users(&mut conn) {
        Ok(rows) => tracing::info!(rows = rows, "добавлены строки в таблицу USERS"),
        Err(e) => tracing::error!(error = %e, "ошибка при вставке строк в таблицу USERS"),
    }

    // Получаем данные из таблицы USERS в структуры Rust и отправляем в Kafka.
    let users = match fetch_users(&mut conn) {
        Ok(users) => {
            tracing::info!(count = users.len(), "прочитаны строки из таблицы USERS");
            users
        }
        Err(e) => {
            tracing::error!(error = %e, "ошибка при чтении таблицы USERS");
            return;
        }
    };

    let (brokers, topic, ..) = kafka::kafka_brokers_and_topic_mix();
    match kafka::send_users_to_kafka(&brokers, &topic, &users).await {
        Ok(()) => tracing::info!(count = users.len(), "данные USERS отправлены в Kafka"),
        Err(e) => tracing::error!(error = %e, "ошибка отправки USERS в Kafka"),
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum UsersTableAction {
    AlreadyExists,
    Created,
}

/// Строка таблицы `USERS` (получение данных из SAP HANA).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UserRow {
    pub id: u64,
    pub name: String,
}

/// Создаёт таблицу `USERS`, если она не существует.
///
/// Возвращает действие: таблица уже была (`AlreadyExists`) или была создана (`Created`).
fn ensure_users_table(
    conn: &mut odbc_api::Connection<'_>,
) -> Result<UsersTableAction, Box<dyn std::error::Error>> {
    if hana_table_exists(conn, "USERS")? {
        return Ok(UsersTableAction::AlreadyExists);
    }

    // SAP HANA: "unsigned" целых типов нет как отдельного типа; используем BIGINT IDENTITY.
    // Имя пользователя — NVARCHAR(255) NOT NULL.
    let ddl = r#"
CREATE TABLE USERS (
  ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  NAME NVARCHAR(255) NOT NULL
)
"#;

    conn.execute(ddl, (), None)?;
    Ok(UsersTableAction::Created)
}

/// Проверяет существование таблицы с именем `table_name_upper` в текущей схеме SAP HANA.
///
/// В HANA имена таблиц в системных представлениях обычно хранятся в верхнем регистре, поэтому ожидается `USERS`, а не `users`.
fn hana_table_exists(
    conn: &mut odbc_api::Connection<'_>,
    table_name_upper: &str,
) -> Result<bool, Box<dyn std::error::Error>> {
    use odbc_api::buffers::TextRowSet;
    use odbc_api::Cursor;

    // SYS.TABLES содержит метаданные таблиц. Имя таблицы в HANA хранится в верхнем регистре.
    // Ограничиваемся текущей схемой.
    let sql = format!(
        "SELECT COUNT(*) FROM SYS.TABLES WHERE SCHEMA_NAME = CURRENT_SCHEMA AND TABLE_NAME = '{}'",
        table_name_upper
    );

    let Some(mut cursor) = conn.execute(&sql, (), None)? else {
        return Ok(false);
    };

    let mut buffers = TextRowSet::for_cursor(1, &mut cursor, Some(64))?;
    let mut row_set_cursor = cursor.bind_buffer(&mut buffers)?;
    let Some(batch) = row_set_cursor.fetch()? else {
        return Ok(false);
    };

    let raw = batch.at(0, 0).unwrap_or(&[]);
    let text = std::str::from_utf8(raw)?.trim();
    let count: u64 = text.parse()?;
    Ok(count > 0)
}

/// Вставляет две тестовые строки в таблицу `USERS`: `User1` и `User2`.
///
/// Возвращаемое значение — число вставленных строк (в этой реализации всегда 2 при успехе).
fn insert_sample_users(conn: &mut odbc_api::Connection<'_>) -> Result<u64, Box<dyn std::error::Error>> {
    use odbc_api::IntoParameter;

    // Вставляем две строки по заданию.
    conn.execute(
        "INSERT INTO USERS (NAME) VALUES (?)",
        (&"User1".into_parameter(),),
        None,
    )?;
    conn.execute(
        "INSERT INTO USERS (NAME) VALUES (?)",
        (&"User2".into_parameter(),),
        None,
    )?;

    // Для отчётности считаем общее количество строк и логируем.
    let count = users_count(conn)?;
    tracing::info!(count = count, "текущее количество строк в USERS");
    Ok(2)
}

/// Возвращает количество строк в таблице `USERS` (`SELECT COUNT(*)`).
fn users_count(conn: &mut odbc_api::Connection<'_>) -> Result<u64, Box<dyn std::error::Error>> {
    use odbc_api::buffers::TextRowSet;
    use odbc_api::Cursor;

    let Some(mut cursor) = conn.execute("SELECT COUNT(*) FROM USERS", (), None)? else {
        return Ok(0);
    };
    let mut buffers = TextRowSet::for_cursor(1, &mut cursor, Some(64))?;
    let mut row_set_cursor = cursor.bind_buffer(&mut buffers)?;
    let Some(batch) = row_set_cursor.fetch()? else {
        return Ok(0);
    };
    let raw = batch.at(0, 0).unwrap_or(&[]);
    let text = std::str::from_utf8(raw)?.trim();
    Ok(text.parse()?)
}

/// Читает пользователей из таблицы `USERS` и возвращает их как `Vec<UserRow>`.
///
/// Выполняет `SELECT ID, NAME FROM USERS ORDER BY ID` и читает результаты через `TextRowSet`.
fn fetch_users(conn: &mut odbc_api::Connection<'_>) -> Result<Vec<UserRow>, Box<dyn std::error::Error>> {
    use odbc_api::buffers::TextRowSet;
    use odbc_api::Cursor;

    let Some(mut cursor) = conn.execute("SELECT ID, NAME FROM USERS ORDER BY ID", (), None)? else {
        return Ok(Vec::new());
    };

    // Читаем построчно небольшими батчами. Для демонстрации достаточно 100 строк за раз.
    let mut buffers = TextRowSet::for_cursor(100, &mut cursor, Some(4096))?;
    let mut row_set_cursor = cursor.bind_buffer(&mut buffers)?;

    let mut out = Vec::new();
    while let Some(batch) = row_set_cursor.fetch()? {
        for row_index in 0..batch.num_rows() {
            let id_raw = batch.at(0, row_index).unwrap_or(&[]);
            let name_raw = batch.at(1, row_index).unwrap_or(&[]);

            let id_text = std::str::from_utf8(id_raw)?.trim();
            let id: u64 = id_text.parse()?;
            let name = String::from_utf8_lossy(name_raw).trim().to_string();

            out.push(UserRow { id, name });
        }
    }

    Ok(out)
}
